apiVersion: k8slab.dev/v1alpha1
kind: Greeting
metadata:
  name: shalom
  namespace: lesson-24
spec:
  message: "shalom from a CRD"
  replicas: 2
---
apiVersion: k8slab.dev/v1alpha1
kind: Greeting
metadata:
  name: boker-tov
  namespace: lesson-24
spec:
  message: "boker tov"
